// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/store.proto

package habitpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HabitServiceClient is the client API for HabitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HabitServiceClient interface {
	GetHabit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Habits, error)
	UpdateHabits(ctx context.Context, in *Habits, opts ...grpc.CallOption) (*UpdateHabitsResponse, error)
}

type habitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHabitServiceClient(cc grpc.ClientConnInterface) HabitServiceClient {
	return &habitServiceClient{cc}
}

func (c *habitServiceClient) GetHabit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Habits, error) {
	out := new(Habits)
	err := c.cc.Invoke(ctx, "/HabitService/GetHabit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *habitServiceClient) UpdateHabits(ctx context.Context, in *Habits, opts ...grpc.CallOption) (*UpdateHabitsResponse, error) {
	out := new(UpdateHabitsResponse)
	err := c.cc.Invoke(ctx, "/HabitService/UpdateHabits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HabitServiceServer is the server API for HabitService service.
// All implementations must embed UnimplementedHabitServiceServer
// for forward compatibility
type HabitServiceServer interface {
	GetHabit(context.Context, *Empty) (*Habits, error)
	UpdateHabits(context.Context, *Habits) (*UpdateHabitsResponse, error)
	mustEmbedUnimplementedHabitServiceServer()
}

// UnimplementedHabitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHabitServiceServer struct {
}

func (UnimplementedHabitServiceServer) GetHabit(context.Context, *Empty) (*Habits, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHabit not implemented")
}
func (UnimplementedHabitServiceServer) UpdateHabits(context.Context, *Habits) (*UpdateHabitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHabits not implemented")
}
func (UnimplementedHabitServiceServer) mustEmbedUnimplementedHabitServiceServer() {}

// UnsafeHabitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HabitServiceServer will
// result in compilation errors.
type UnsafeHabitServiceServer interface {
	mustEmbedUnimplementedHabitServiceServer()
}

func RegisterHabitServiceServer(s grpc.ServiceRegistrar, srv HabitServiceServer) {
	s.RegisterService(&HabitService_ServiceDesc, srv)
}

func _HabitService_GetHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).GetHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HabitService/GetHabit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).GetHabit(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HabitService_UpdateHabits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Habits)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HabitServiceServer).UpdateHabits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HabitService/UpdateHabits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HabitServiceServer).UpdateHabits(ctx, req.(*Habits))
	}
	return interceptor(ctx, in, info, handler)
}

// HabitService_ServiceDesc is the grpc.ServiceDesc for HabitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HabitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HabitService",
	HandlerType: (*HabitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHabit",
			Handler:    _HabitService_GetHabit_Handler,
		},
		{
			MethodName: "UpdateHabits",
			Handler:    _HabitService_UpdateHabits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/store.proto",
}
